# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "go-authenticator-patch" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Build for linux mips
      run: CGO_ENABLED=0 GOARCH=mips go build -ldflags="-w -s" -o ./build/auth_mips auth

    - name: Build for linux arm
      run: CGO_ENABLED=0 GOARCH=arm go build -ldflags="-w -s" -o ./build/auth_arm auth

    - name: Build for linux amd64
      run: CGO_ENABLED=0 GOARCH=amd64 go build -ldflags="-w -s" -o ./build/auth_amd64 auth

    - name: Build for Windows amd64
      run: GOOS=windows CGO_ENABLED=0 GOARCH=amd64 go build -ldflags="-w -s" -o ./build/auth_amd64.exe auth
      
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: builds
        path: ./build/
